export const SIMULATION_CONFIG = {
  version: "simulation.v9",
  ratings: {
    minimum: 25,
    maximum: 99,
    baseline: 75,
    offenseWeights: { shooting: 0.28, finishing: 0.24, playmaking: 0.22, basketballIq: 0.14, athleticism: 0.12 },
    defenseWeights: { perimeterDefense: 0.32, interiorDefense: 0.32, rebounding: 0.18, basketballIq: 0.12, athleticism: 0.06 },
  },
  leagueBasePace: 99.5,
  paceMin: 92,
  paceMax: 106,
  paceNoise: 2.5,
  paceAthleticismWeight: 0.06,
  leagueAverageOrtg: 114,
  talentBaseline: 75,
  talentOffenseScale: 0.45,
  talentDefenseScale: 0.4,
  homeOrtgModifier: 0.9,
  awayOrtgModifier: -0.9,
  efficiencyNoiseSd: 5.5,
  playoffNoiseMultiplier: 0.9,
  starPower: { baseline: 75, weight: 0.1, bestStarWeight: 0.65, secondStarWeight: 0.35, regularSeasonCap: 2, postseasonCap: 3 },
  garbageTime: { scoreMarginThreshold: 18, fourthQuarterStartMinute: 6, starterMinutesReduction: 3, minimumStarterSecondsAfterReduction: 60 },
  scoring: { minimumTeamScore: 65, periodWeightMinimum: 0.82, periodWeightRange: 0.36, overtimePeriodWeight: 0.32, overtimePointsBase: 11.5, overtimePointsNoise: 2.2, overtimePointsMinimum: 5 },
  formModifierMin: -1.5,
  formModifierMax: 1.5,
  moralePenaltyFloor: 15,
  moraleNoPenaltyThreshold: 50,
  moraleMaxPenalty: 1.5,
  defaultMorale: 50,
  fatigue: {
    noPenaltyThreshold: 60,
    maxPenalty: 3,
    penaltyPerPoint: 0.075,
    baseGameLoad: 3,
    minutesLoad: 0.32,
    backToBackLoad: 5,
    ageLoadAfter30: 0.32,
    athleticismRelief: 0.08,
    recoveryPerRestDay: 8,
    recoveryPerFatiguePoint: 0.08,
  },
  coaching: {
    regularEfficiencyPoints: 1,
    playoffEfficiencyPoints: 1.5,
    reviewFatigueRecovery: 18,
    reviewTeamMoraleBoost: 1,
    reviewTwoPlayerMoraleBoost: 1,
    reviewTeamFatigueRecovery: 1,
    highFatigueThreshold: 60,
    lowMoraleThreshold: 50,
  },
  regulationTeamSeconds: 5 * 48 * 60,
  overtimeTeamSeconds: 5 * 5 * 60,
  rotation: {
    maximumPlayers: 12,
    minimumPlayers: 5,
    overtimePlayers: 5,
    franchiseCoreMinuteBonus: 2,
    keyPlayerMinuteBonus: 1,
    regularSeasonMaximumMinutes: 40,
    postseasonMaximumMinutes: 42,
    fatigueAdjustmentThreshold: 60,
    fatigueAdjustmentDivisor: 250,
  },
  roleMinutes: {
    STARTER: 32,
    SIXTH_MAN: 26,
    ROTATION: 18,
    BENCH: 8,
    OUT: 0,
  },
  usageRoleMultiplier: {
    FRANCHISE_CORE: 1.15,
    KEY_PLAYER: 1.08,
    ROTATION: 1,
    DEVELOPMENT: 0.9,
    BENCH: 0.8,
  },
  boxScore: {
    turnover: { baseRate: 0.14, playmakingCoefficient: 0.00035, iqCoefficient: 0.00025, noise: 0.008, minimumRate: 0.09, maximumRate: 0.19 },
    freeThrows: { baseRate: 0.23, finishingCoefficient: 0.0015, noise: 0.015, minimumRate: 0.15, maximumRate: 0.34, possessionCoefficient: 0.44 },
    offensiveRebounds: { baseRate: 0.115, reboundingCoefficient: 0.0012, noise: 0.01, minimumRate: 0.07, maximumRate: 0.18 },
    threeRate: { minimum: 0.25, maximum: 0.55 },
    reconciliation: { fgaDeltaMin: -4, fgaDeltaMax: 8, threePaDeltaMin: -5, threePaDeltaMax: 5, ftaDeltaMin: -6, ftaDeltaMax: 8, minimumFga: 60, minimumThreePa: 15, minimumTwoPointAttempts: 10, minimumFta: 8, targetThreePointPercentage: 0.36, targetFreeThrowPercentage: 0.78 },
    rebounds: {
      defensiveBase: 32,
      noise: 3,
      positionWeight: { PG: 0.75, SG: 0.8, SF: 0.95, PF: 1.15, C: 1.4 },
    },
    assists: {
      baseMadeFieldGoalRate: 0.67,
      playmakingCoefficient: 0.003,
      minimumRate: 0.5,
      maximumRate: 0.82,
      minimum: 8,
      playmakingFloor: 25,
      iqBaseline: 75,
      positionWeight: { PG: 1.25, SG: 1.05, SF: 0.95, PF: 0.85, C: 0.9 },
    },
    steals: { base: 7, noise: 1.5, minimum: 2 },
    blocks: { base: 5, noise: 1.3, minimum: 1 },
    usage: { tendencyWeight: 0.55, offenseImpactWeight: 0.45 },
    playerGameVariation: {
      minimumMultiplier: 0.55,
      maximumMultiplier: 1.45,
      usageSd: 0.23,
      shootingSd: 0.18,
      reboundSd: 0.25,
      assistSd: 0.28,
    },
  },
  playerStatus: {
    fatigueMinimumGameLoad: 2,
    ageLoadStart: 30,
    athleticismReliefStart: 70,
    pointsPer36Seconds: 2160,
    expectedPointsBase: 5,
    expectedPointsUsageWeight: 0.19,
    formPerformanceDivisor: 18,
    formDeltaMinimum: -0.55,
    formDeltaMaximum: 0.55,
    formCarryover: 0.78,
    formMinimum: -3,
    formMaximum: 3,
  },
} as const;
