export const BALANCE_CONFIG = {
  version: "balance.v8-trade-value",
  freeAgency: {
    offerValidDays: 3,
    decisionWindowDays: 3,
    maxActiveOffersPerPlayer: 5,
    earlyAcceptThreshold: 85,
    minimumAcceptThreshold: 60,
    preferenceNoiseMin: -3,
    preferenceNoiseMax: 3,
    marketSalary: {
      ratingAnchors: [
        { overall: 65, annualSalary: 1_272_870 },
        { overall: 70, annualSalary: 2_500_000 },
        { overall: 75, annualSalary: 8_000_000 },
        { overall: 80, annualSalary: 20_000_000 },
        { overall: 85, annualSalary: 38_000_000 },
        { overall: 90, annualSalary: 50_000_000 },
      ],
      youngMaximumAge: 25,
      youngMultiplier: 1.05,
      veteranMinimumAge: 32,
      veteranMultiplier: 0.95,
    },
    roleOverallThresholds: { starter: 82, sixthMan: 74, rotation: 65 },
    utilityScales: { salary: 70, contractYears: 80, roleBase: 70, roleStep: 15 },
    ageCareerStage: {
      youngMaximumAge: 25,
      veteranMinimumAge: 31,
      targetYears: { young: 4, prime: 3, veteran: 2 },
      young: { years: 20, role: 0.2 },
      prime: { salary: 0.45, contender: 0.3, role: 0.25 },
      veteran: { guaranteed: 0.6, contender: 0.4 },
    },
    contenderStarValueThreshold: 78,
    contenderStarBonus: 12,
    originalTeamRelationship: 100,
    otherTeamRelationship: 45,
    weights: {
      salaryValue: 30,
      guaranteedMoney: 15,
      contractYears: 8,
      promisedRole: 12,
      teamRecord: 7,
      contenderStatus: 10,
      franchiseReputation: 6,
      marketPreference: 3,
      existingTeamRelationship: 5,
      ageCareerStageFit: 4,
    },
    marketPreferenceModel: {
      baseline: 50,
      youngMaximumAge: 25,
      veteranMinimumAge: 31,
      youngBonus: 3,
      veteranPenalty: -3,
      personalityBias: {
        COMPETITIVE: 0,
        MONEY_FOCUSED: -8,
        LOYAL: -12,
        ROLE_FOCUSED: -8,
        MARKET_FOCUSED: 28,
        BALANCED: 0,
      },
    },
    marketFit: { baseline: 50, scale: 50 },
    personalityWeightShifts: {
      COMPETITIVE: { salaryValue: -5, guaranteedMoney: -3, teamRecord: 2, contenderStatus: 8, marketPreference: -2 },
      MONEY_FOCUSED: { salaryValue: 7, guaranteedMoney: 5, teamRecord: -3, contenderStatus: -4, marketPreference: -2, existingTeamRelationship: -3 },
      LOYAL: { salaryValue: -4, guaranteedMoney: -2, marketPreference: -2, existingTeamRelationship: 8 },
      ROLE_FOCUSED: { salaryValue: -4, guaranteedMoney: -2, promisedRole: 8, marketPreference: -2 },
      MARKET_FOCUSED: { salaryValue: -5, guaranteedMoney: -2, marketPreference: 10, existingTeamRelationship: -3 },
      BALANCED: {},
    },
  },
  ai: {
    directionLockDays: 60,
    deterministicVarianceMin: -3,
    deterministicVarianceMax: 3,
    maxNewFreeAgentOffersPerTeamDay: 3,
    tradeAcceptanceThreshold: -0.5,
    maxTradesPerTeamSeason: 3,
    tradeDeadlineDateIndex: 105,
    tradeCandidatePlayersPerTeam: 8,
    tradePartnerTeamsPerEvaluation: 8,
    rosterNeedTargetPerPosition: 3,
    rosterNeedFloor: -2,
    rosterNeedWeight: 0.8,
    careerDaysPerSeason: 200,
    directionWinRateThresholds: { contend: 0.62, compete: 0.48, retool: 0.35 },
    directionWeights: {
      CONTEND: { currentAbility: 1, youth: 0, starterBonus: 2 },
      COMPETE: { currentAbility: 1, youth: 0, starterBonus: 0 },
      RETOOL: { currentAbility: 1, youth: 0.35, starterBonus: 0 },
      REBUILD: { currentAbility: 1, youth: 0.7, starterBonus: 0 },
    },
    draftPreference: { readinessWeight: 0.72, potentialWeight: 0.28, futureFirstPotentialWeight: 0.45, rosterNeedWeight: 1.6, agePenalty: 0.15 },
    freeAgency: { minimumTargetValue: 0, rfaMatchValue: 70, salaryOfferMinMultiplier: 0.9, salaryOfferMaxMultiplier: 1.1, longOfferMaximumAge: 27, longOfferYears: 3, veteranOfferYears: 2, guaranteedPercent: 0.85 },
  },
  trade: {
    valueWeights: { futureFirstAge: 1.2, winNowAge: 0.65, balancedAge: 0.8 },
    valueLimits: { futureFirstAgeFloor: -8, winNowAgeFloor: -6, balancedAgeFloor: -7 },
    abilityValueAnchors: [
      { overall: 55, value: 3 }, { overall: 60, value: 8 }, { overall: 65, value: 14 },
      { overall: 70, value: 22 }, { overall: 75, value: 34 }, { overall: 80, value: 50 },
      { overall: 85, value: 68 }, { overall: 90, value: 86 }, { overall: 95, value: 104 },
    ],
    potentialBonusByGrade: { S: 10, "A+": 8, A: 6, "B+": 4, B: 2, C: 0, D: 0 },
    potentialBonusFullAge: 20,
    potentialBonusEndAge: 28,
    contractValueDivisor: 3_000_000,
    contractValueLimit: 12,
    contractTermFirstYearWeight: 0.35,
    contractTermAdditionalYearWeight: 0.22,
    salaryValueDivisor: 4_000_000,
    refreshPenaltyByInquiry: [0, 1, 2, 3],
    addSecondRoundPickValueGap: 3,
    generatedOfferCount: 3,
    futurePickHorizonYears: 7,
    draftPickValue: { firstRound: 20, secondRound: 3, yearlyDecay: 0.86, lotteryPremium: 1.5, lateFirstMultiplier: 0.65, lateSecondMultiplier: 0.75, lotterySecondMultiplier: 1.25 },
    ageValue: { futureFirstTargetAge: 27, winNowCenterAge: 28, winNowBase: 3, balancedTargetAge: 29 },
    negativeContract: { salaryMillionsDivisor: 1_000_000, playerValueMultiplier: 0.18 },
  },
  contracts: {
    teamOptionThreshold: 65,
    playerOptionNoiseMin: -3,
    playerOptionNoiseMax: 3,
    teamOption: { youngMaximumAge: 25, veteranMinimumAge: 32, youngBonus: 5, veteranPenalty: -5, starterBonus: 4, outPenalty: -4, salaryDivisor: 4_000_000 },
    playerOption: { moneyFocusedBonus: 4, loyalBonus: 2, competitivePenalty: -2, lowInjuryRatingThreshold: 55, lowInjuryRatingBonus: 3 },
  },
  playerLifecycle: {
    snapshotSeasonYear: 2026,
    attributeMinimum: 25,
    attributeMaximum: 99,
    maximumAnnualGrowth: 4,
    maximumAnnualRegression: -6,
    ageCurve: {
      age21AndUnder: 1.8,
      age22To25: 1.35,
      age26To29: 0.25,
      age30To32: -0.65,
      age33To35: -1.45,
      age36AndOver: -2.35,
    },
    regressionMultipliers: {
      shooting: 0.35,
      finishing: 1.1,
      playmaking: 0.5,
      perimeterDefense: 1.05,
      interiorDefense: 0.8,
      rebounding: 0.75,
      athleticism: 1.4,
      basketballIq: 0.25,
    },
    development: {
      minutesBands: [
        { minimumMinutes: 28, multiplier: 1.12 },
        { minimumMinutes: 18, multiplier: 1 },
        { minimumMinutes: 8, multiplier: 0.88 },
        { minimumMinutes: 0, multiplier: 0.72 },
      ],
      roleMultipliers: { development: 1.08, coreOrStarter: 1.04, out: 0.82, default: 1 },
      potentialGapDivisor: 12,
      potentialInfluenceMin: 0.18,
      potentialInfluenceMax: 1.35,
      developmentRateMin: 0.82,
      developmentRateRange: 0.36,
      volatilityMin: 0.12,
      volatilityRange: 0.3,
      healthBase: 0.72,
      injuryRatingDivisor: 350,
      iqBase: 0.88,
      iqDivisor: 600,
      regressionBase: 1.12,
      regressionInjuryDivisor: 500,
    },
    retirement: {
      ageProbability: [
        { minimumAge: 40, probability: 0.86 },
        { minimumAge: 39, probability: 0.7 },
        { minimumAge: 38, probability: 0.5 },
        { minimumAge: 37, probability: 0.32 },
        { minimumAge: 36, probability: 0.2 },
        { minimumAge: 35, probability: 0.12 },
        { minimumAge: 31, probability: 0.02 },
        { minimumAge: 0, probability: 0.002 },
      ],
      overallBaseline: 70,
      overallProbabilityPerPoint: 0.012,
      overallModifierMin: -0.04,
      overallModifierMax: 0.22,
      underContractReduction: 0.08,
      starterReduction: 0.06,
      lowInjuryRatingThreshold: 50,
      lowInjuryRatingAddition: 0.08,
      competitiveReduction: 0.025,
      unemploymentAgeMinimum: 32,
      unemploymentDaysThreshold: 180,
      unemploymentAddition: 0.25,
      unemploymentYearsThreshold: 2,
      unemploymentProbabilityFloor: 0.92,
      probabilityMin: 0.001,
      probabilityMax: 0.97,
      offseasonUnemploymentDays: 180,
    },
    hallOfFame: {
      threshold: 75,
      awardWeights: { mvp: 25, finalsMvp: 20, dpoy: 15, championships: 10, allStar: 5, roy: 5, sixthMan: 3, mip: 2 },
      production: { pointsDivisor: 1800, reboundsDivisor: 2500, assistsDivisor: 2200, maximum: 15 },
      peak: { baseline: 70, multiplier: 0.75, maximum: 15 },
      longevity: { perSeason: 0.65, maximum: 10 },
      nonAwardMaximum: 40,
    },
    ageCalculation: { seasonMonth: 10, seasonDay: 20, minimumAge: 18 },
    hiddenPotential: { youngMaximumAge: 23, minimumGap: 2, youngMaximumGap: 15, olderMaximumGap: 7 },
    changeReportEpsilon: 0.1,
  },
  training: {
    maxFocusedPlayers: 2,
    weights: {
      BALANCED: { shooting: 1.08, finishing: 1.08, playmaking: 1.08, perimeterDefense: 1.08, interiorDefense: 1.08, rebounding: 1.08, athleticism: 1.08, basketballIq: 1.08 },
      SHOOTING: { shooting: 1.4, finishing: 0.94, playmaking: 0.94, perimeterDefense: 0.94, interiorDefense: 0.94, rebounding: 0.94, athleticism: 0.94, basketballIq: 0.94 },
      PLAYMAKING: { shooting: 0.94, finishing: 0.94, playmaking: 1.4, perimeterDefense: 0.94, interiorDefense: 0.94, rebounding: 0.94, athleticism: 0.94, basketballIq: 1.08 },
      DEFENSE: { shooting: 0.92, finishing: 0.92, playmaking: 0.92, perimeterDefense: 1.28, interiorDefense: 1.28, rebounding: 1.04, athleticism: 0.92, basketballIq: 1.04 },
      INSIDE: { shooting: 0.91, finishing: 1.2, playmaking: 0.91, perimeterDefense: 0.91, interiorDefense: 1.2, rebounding: 1.2, athleticism: 1.02, basketballIq: 0.91 },
      ATHLETICISM: { shooting: 0.9, finishing: 1.12, playmaking: 0.9, perimeterDefense: 0.9, interiorDefense: 0.9, rebounding: 0.9, athleticism: 1.45, basketballIq: 0.9 },
    },
  },
  injuries: {
    basePerPlayerGameProbability: 0.0035,
    majorSeverityThreshold: "LONG",
    recentEventLimit: 20,
    durationGames: {
      MINOR: [1, 3],
      SHORT: [4, 8],
      MEDIUM: [9, 20],
      LONG: [21, 45],
      SEASON_ENDING: [60, 99],
    },
    severityWeights: { MINOR: 55, SHORT: 23, MEDIUM: 13, LONG: 7, SEASON_ENDING: 2 },
    injuryRatingInfluence: { baseline: 100, divisor: 70, baseMultiplier: 0.62, riskMultiplier: 0.86 },
    minutes: { baseMultiplier: 0.72, referenceMinutes: 36, maximumRatio: 1.25, multiplier: 0.45 },
    ageMultipliers: { age25AndUnder: 0.9, age26To30: 1, age31To34: 1.16, age35AndOver: 1.34 },
    fatigueDivisor: 220,
    history: { maximumAddition: 0.45, missedGamesDivisor: 360 },
    severityAdjustment: { ageStart: 30, agePerYear: 0.006, injuryRatingStart: 65, injuryRatingPerPoint: 0.003 },
    healthAfterInjury: { MINOR: 85, SHORT: 72, MEDIUM: 55, LONG: 35, SEASON_ENDING: 15 },
  },
  draft: {
    classSize: 80,
    rounds: 2,
    lotteryDrawCount: 4,
    lotteryWeights: [14, 14, 14, 12, 10.5, 9, 7.5, 6, 4.5, 3, 2, 1.5, 1, 0.7, 0.2, 0.1],
    potentialDistribution: { base: 96, rankSlope: 0.35, noise: 7, minimum: 55, maximum: 99, readinessGapMinimum: 2 },
    archetypeDistribution: { positions: { PG: 20, SG: 20, SF: 20, PF: 20, C: 20 }, traits: { PRIMARY_CREATOR: 10, SECONDARY_CREATOR: 10, SPACER: 10, SLASHER: 10, RIM_RUNNER: 10, WING_STOPPER: 10, RIM_PROTECTOR: 10, REBOUNDER: 10, TWO_WAY: 10, SIXTH_MAN: 10 } },
    scouting: { confidenceBase: 94, rankSlope: 0.62, confidenceNoise: 6, confidenceMin: 35, confidenceMax: 96, errorByConfidence: [{ minimumConfidence: 85, error: 2 }, { minimumConfidence: 70, error: 5 }, { minimumConfidence: 50, error: 9 }, { minimumConfidence: 0, error: 13 }] },
    readinessTiers: [{ rankExclusive: 8, base: 85, noise: 5 }, { rankExclusive: 18, base: 75, noise: 5 }, { rankExclusive: 42, base: 66, noise: 7 }, { rankExclusive: 999, base: 59, noise: 7 }],
    age: { base: 18, topRankExclusive: 30, topRange: 3, remainingRange: 4 },
    developmentRateTiers: [{ rankExclusive: 8, minimum: 1, range: 0.25 }, { rankExclusive: 18, minimum: 0.82, range: 0.43 }, { rankExclusive: 999, minimum: 0.75, range: 0.5 }],
    potentialGrades: [{ minimum: 94, grade: "S", publicValue: 98 }, { minimum: 89, grade: "A+", publicValue: 92 }, { minimum: 84, grade: "A", publicValue: 87 }, { minimum: 79, grade: "B+", publicValue: 81 }, { minimum: 74, grade: "B", publicValue: 76 }, { minimum: 66, grade: "C", publicValue: 68 }, { minimum: 0, grade: "D", publicValue: 58 }],
    tendencies: { threeRateMinimum: 0.2, threeRateRange: 0.34, assistRateMinimum: 0.08, assistRateRange: 0.28, rimRateMinimum: 0.18, rimRateRange: 0.47, usageMinimum: 42, usageRange: 48 },
    developmentVolatility: { minimum: 0.08, range: 0.42 },
    scoutingPotentialMinimum: 50,
    initialHealth: 100,
    initialMorale: 50,
    historicalRebirth: {
      enabled: true,
      mode: "LEGEND_ARCHETYPE" as const,
      firstEligibleSeasonYear: 2027,
      classShare: 0.0375,
      maximumPerClass: 3,
      rookieAttributeJitter: 3,
      potentialJitter: 4,
      reusePerCareer: 1,
    },
  },
  randomEvents: {
    triggerEveryUserGames: 6,
    triggerProbability: 1,
    defaultCooldownGames: 10,
    defaultWeight: 20,
    categoryWeights: { INJURY: 20, MORALE: 20, ROLE: 20, BREAKOUT: 20, SLUMP: 20, TRADE: 20, STREAK: 20, ROOKIE: 20, EXPANSION: 20, PLAYOFFS: 20, FRANCHISE: 20, DRAFT: 20, FREE_AGENCY: 20, RFA: 20, AI_GM: 20 },
    losingStreakRecovery: { minimumLosses: 3, weightMultiplier: 1.75 },
    streakThresholds: [3, 5, 10],
    breakoutPointsThreshold: 32,
    moraleEventThreshold: 35,
    leagueLogLimit: 100,
    status: { minimum: 0, maximum: 100, defaultMorale: 50, formMinimum: -3, formMaximum: 3 },
  },
  leagueBalance: {
    annualRookieInflow: 80,
    retirementPopulationTarget: { minimum: 55, maximum: 85 },
    overallTargets: { averageMinimum: 68, averageMaximum: 76, elite90PlusMinimum: 4, elite90PlusMaximum: 18 },
  },
  overall: {
    attributeWeightsByPosition: {
      PG: { shooting: 0.18, finishing: 0.15, playmaking: 0.24, perimeterDefense: 0.13, interiorDefense: 0.03, rebounding: 0.04, athleticism: 0.10, basketballIq: 0.13 },
      SG: { shooting: 0.22, finishing: 0.18, playmaking: 0.14, perimeterDefense: 0.15, interiorDefense: 0.04, rebounding: 0.05, athleticism: 0.11, basketballIq: 0.11 },
      SF: { shooting: 0.17, finishing: 0.17, playmaking: 0.12, perimeterDefense: 0.16, interiorDefense: 0.09, rebounding: 0.10, athleticism: 0.10, basketballIq: 0.09 },
      PF: { shooting: 0.12, finishing: 0.17, playmaking: 0.09, perimeterDefense: 0.10, interiorDefense: 0.18, rebounding: 0.16, athleticism: 0.10, basketballIq: 0.08 },
      C: { shooting: 0.06, finishing: 0.18, playmaking: 0.09, perimeterDefense: 0.05, interiorDefense: 0.25, rebounding: 0.22, athleticism: 0.08, basketballIq: 0.07 },
    },
  },
  teamOverall: {
    rawScale: 2.4,
    rawOffset: -110,
    minimum: 50,
    maximum: 99,
  },
  rotationPlan: {
    regulationMinutes: 240,
    minimumActivePlayers: 5,
    maximumActivePlayers: 12,
    regularSeasonMaximumMinutes: 40,
    postseasonMaximumMinutes: 42,
    defaultMinuteWeights: [34, 34, 33, 32, 31, 26, 18, 14, 10, 8],
    /** Auto-assignment preference only; a secondary position still has no in-game mismatch penalty. */
    secondaryPositionAssignmentPenalty: 2,
    /** Primary-position distance after an exact secondary-position match has already been ruled out. */
    positionMismatchPenaltyByDistance: [0, 1.5, 4, 8, 14],
  },
  achievements: {
    EXPANSION_COMPLETE: { label: "新球队诞生", trigger: { type: "EXPANSION_COMPLETE", value: 1 }, reward: { dynastyScore: 25 } },
    FIRST_WIN: { label: "队史首胜", trigger: { type: "CAREER_WINS", value: 1 }, reward: { dynastyScore: 10 } },
    TEN_WINS: { label: "初具竞争力", trigger: { type: "CAREER_WINS", value: 10 }, reward: { dynastyScore: 15 } },
    TWENTY_FIVE_WINS: { label: "稳步前行", trigger: { type: "CAREER_WINS", value: 25 }, reward: { dynastyScore: 20 } },
    FIFTY_CAREER_WINS: { label: "五十胜里程", trigger: { type: "CAREER_WINS", value: 50 }, reward: { dynastyScore: 30 } },
    HUNDRED_WINS: { label: "百胜经理", trigger: { type: "CAREER_WINS", value: 100 }, reward: { dynastyScore: 50 } },
    TWO_HUNDRED_WINS: { label: "两百胜名帅", trigger: { type: "CAREER_WINS", value: 200 }, reward: { dynastyScore: 80 } },
    FIRST_PLAY_IN: { label: "第一次附加赛", trigger: { type: "PLAY_IN", value: 1 }, reward: { dynastyScore: 15 } },
    FIRST_PLAYOFFS: { label: "季后赛初体验", trigger: { type: "PLAYOFFS", value: 1 }, reward: { dynastyScore: 25 } },
    FIRST_SERIES_WIN: { label: "系列赛突破", trigger: { type: "SERIES_WINS", value: 1 }, reward: { dynastyScore: 40 } },
    TWO_SERIES_WINS: { label: "挺进四强", trigger: { type: "SERIES_WINS", value: 2 }, reward: { dynastyScore: 50 } },
    THREE_SERIES_WINS: { label: "冲出分区", trigger: { type: "SERIES_WINS", value: 3 }, reward: { dynastyScore: 70 } },
    CONFERENCE_FINALS: { label: "分区决赛", trigger: { type: "CONFERENCE_FINALS", value: 1 }, reward: { dynastyScore: 60 } },
    FINALS_APPEARANCE: { label: "总决赛", trigger: { type: "FINALS", value: 1 }, reward: { dynastyScore: 80 } },
    FIRST_CHAMPIONSHIP: { label: "首冠", trigger: { type: "CHAMPIONSHIPS", value: 1 }, reward: { dynastyScore: 150 } },
    SECOND_CHAMPIONSHIP: { label: "再捧奖杯", trigger: { type: "CHAMPIONSHIPS", value: 2 }, reward: { dynastyScore: 180 } },
    THIRD_CHAMPIONSHIP: { label: "三冠基业", trigger: { type: "CHAMPIONSHIPS", value: 3 }, reward: { dynastyScore: 250 } },
    THIRTY_WIN_SEASON: { label: "赛季三十胜", trigger: { type: "SEASON_WINS", value: 30 }, reward: { dynastyScore: 20 } },
    FORTY_WIN_SEASON: { label: "赛季四十胜", trigger: { type: "SEASON_WINS", value: 40 }, reward: { dynastyScore: 25 } },
    FIFTY_WIN_SEASON: { label: "50胜", trigger: { type: "SEASON_WINS", value: 50 }, reward: { dynastyScore: 30 } },
    SIXTY_WIN_SEASON: { label: "60胜", trigger: { type: "SEASON_WINS", value: 60 }, reward: { dynastyScore: 50 } },
    HOMEGROWN_ALL_STAR: { label: "自家球星", trigger: { type: "HOMEGROWN_ALL_STAR", value: 1 }, reward: { dynastyScore: 35 } },
    ROOKIE_OF_YEAR: { label: "最佳新秀", trigger: { type: "ROOKIE_OF_YEAR", value: 1 }, reward: { dynastyScore: 40 } },
    MVP_WINNER: { label: "联盟最有价值", trigger: { type: "MVP_WINNER", value: 1 }, reward: { dynastyScore: 80 } },
    DPOY_WINNER: { label: "防守之王", trigger: { type: "DPOY_WINNER", value: 1 }, reward: { dynastyScore: 60 } },
    MOST_IMPROVED_WINNER: { label: "进步之星", trigger: { type: "MIP_WINNER", value: 1 }, reward: { dynastyScore: 40 } },
    SIXTH_MAN_WINNER: { label: "最佳第六人", trigger: { type: "SIXTH_MAN_WINNER", value: 1 }, reward: { dynastyScore: 40 } },
    DYNASTY_TWO_OF_THREE: { label: "王朝雏形", trigger: { type: "CHAMPIONSHIPS_IN_YEARS", value: 2, window: 3 }, reward: { dynastyScore: 200 } },
  },
  expansion: {
    aiStrategyWeights: { FUTURE_FIRST: 40, BALANCED: 40, WIN_NOW: 20 },
    maxAcceptedTradesPerTeam: 5,
    aiAcceptedTradeTarget: 2,
    protectPlayerOfferProbability: 0.45,
    protectedPlayersPerExistingTeam: 8,
    rosterPlayersPerExpansionTeam: 14,
    optionExerciseProbability: 0.7,
    protectionValue: {
      starOverallThreshold: 82,
      starAssetBonusPerOverall: 1.25,
      expiringHighSalaryCapShare: 0.18,
      expiringHighSalaryBonus: 4,
      twoYearHighSalaryBonus: 1,
      durabilityRiskThreshold: 75,
      durabilityRiskPenaltyPerPoint: 0.15,
      currentInjuryPenaltyPerGame: 0.08,
      currentInjuryPenaltyMaximum: 4,
      contenderAbilityThreshold: 80,
      contenderAbilityBonusPerOverall: 0.7,
      competeAbilityBonusPerOverall: 0.5,
      retoolAbilityBonusPerOverall: 0.2,
      rebuildVeteranAge: 32,
      rebuildVeteranHighSalaryPenalty: 30,
    },
    package: {
      A: { firstExpansionPick: 1, rookieDraftPick: 6 },
      B: { firstExpansionPick: 2, rookieDraftPick: 5 },
    },
    compensationPick: { startYear: 2027, yearWindow: 5, protectPlayerRound: 2, selectPlayerRound: 1 },
  },
  teamFit: {
    attributeFloor: 25,
    positionCount: 5,
    rotationSize: 10,
    topUnitSize: 7,
    benchStartIndex: 5,
    benchEndIndex: 10,
    creatorWeights: { primary: 0.62, secondary: 0.38 },
    starWeights: { primary: 0.65, secondary: 0.35 },
    spacingWeights: { shooting: 0.72, threeRate: 0.28 },
    rimProtectionPlayers: 2,
    defaultHeightCm: 198,
    idealAverageHeightCm: 201,
    heightPenaltyPerCm: 3,
    sizeWeights: { positionCoverage: 0.55, heightBalance: 0.45 },
    highUsageThreshold: 75,
    acceptableHighUsagePlayers: 2,
    conflictPenaltyPerExtraPlayer: 12,
    conflictUsageBaseline: 82,
    conflictUsagePenalty: 0.6,
    conflictScoreBaseline: 90,
    scoreWeights: { creation: 0.17, spacing: 0.15, perimeterDefense: 0.14, rimProtection: 0.14, rebounding: 0.12, sizeBalance: 0.1, benchDepth: 0.1, usageConflict: 0.08 },
    modifier: { baseline: 50, divisor: 10, minimum: -5, maximum: 5 },
    healthFallbackAvailable: 100,
    healthFallbackUnavailable: 55,
    gradeThresholds: [{ minimum: 90, grade: "S" }, { minimum: 84, grade: "A+" }, { minimum: 76, grade: "A" }, { minimum: 69, grade: "B+" }, { minimum: 61, grade: "B" }, { minimum: 53, grade: "C+" }, { minimum: 45, grade: "C" }, { minimum: 0, grade: "D" }],
  },
  teamCore: {
    // City exposure tuning, not population or revenue estimates.
    marketRatings: {
      SEA: 74, POR: 70, SAC: 68, GSW: 96, LVG: 82, PHX: 78, LAL: 100, LAC: 100,
      UTA: 61, DEN: 73, OKC: 58, DAL: 83, HOU: 83, SAS: 66, MEM: 60, NOP: 59,
      BOS: 87, BKN: 100, NYK: 100, TOR: 83, PHI: 84, WAS: 80, CLE: 66, DET: 68,
      MIN: 72, MIL: 67, CHI: 93, IND: 66, ATL: 81, CHA: 65, ORL: 72, MIA: 88,
    },
    gameFanSupport: { win: 0.25, loss: -0.15, winningStreakThreshold: 3, losingStreakThreshold: 5, streakBonus: 0.1, streakPenalty: -0.1 },
    morale: { win: 0.35, loss: -0.45, nonParticipantMultiplier: 0.4, default: 50 },
    fanMilestones: { playIn: 1, playoffs: 3, seriesWin: 2, conferenceFinals: 3, finals: 4, champion: 8 },
    reputation: { poorSeasonWins: 25, poorSeasonPenalty: -3, mediocreSeasonWins: 34, mediocreSeasonPenalty: -1, playoffs: 2, conferenceFinals: 4, finals: 6, champion: 10, mvp: 3, roy: 1, seasonMinimum: -5, seasonMaximum: 12 },
    freeAgentAttractionWeights: { franchiseReputation: 0.35, fanSupport: 0.25, contenderScore: 0.2, marketRating: 0.2 },
  },
  awards: {
    minimumCandidateGames: 10,
    availabilityGames: 65,
    allStarsPerConference: 12,
    productionWeights: { points: 1, rebounds: 1.15, assists: 1.45, steals: 2.2, blocks: 2.1, turnovers: -0.8 },
    teamWinScoreMaximum: 14,
    dpoyWeights: { steals: 4, blocks: 4.5, rebounds: 0.5, perimeterDefense: 0.12, interiorDefense: 0.12, teamWins: 0.45 },
    rookie: { maximumServiceYears: 1, maximumAge: 24 },
    mostImproved: { minimumGames: 41, fallbackMaximumAge: 27, seasonGamesDivisor: 82, previousSeasonMinimumGames: 20 },
  },
  historyCompression: {
    fullSeasonsToKeep: 1,
    recordThresholds: { points: 60, rebounds: 25, assists: 20, steals: 8, blocks: 10 },
    finalsDateOffset: 140,
    decidingSeriesGameCount: 7,
  },
  scheduleQuality: {
    maximumHomeStreak: 6,
    maximumAwayStreak: 5,
    minimumBackToBacks: 12,
    maximumBackToBacks: 16,
    targetBackToBacks: 14,
    optimizerRestarts: 180,
    optimizerSteps: 700,
  },
  replacementPlayers: {
    ageMinimum: 24,
    ageMaximum: 32,
    attributeBase: 57,
    attributeMinimum: 48,
    attributeMaximum: 66,
    attributeNoise: 4,
    threeRateMinimum: 0.24,
    threeRateRange: 0.2,
    assistRateMinimum: 0.08,
    assistRateRange: 0.2,
    rimRateMinimum: 0.2,
    rimRateRange: 0.34,
    usageMinimum: 35,
    usageMaximum: 58,
    initialMorale: 45,
  },
  rosterRotation: { starters: 5, sixthManIndex: 5, rotationEndIndex: 10 },
  injuryRecovery: { maximumHealthBeforeFullRecovery: 95, defaultInjuredHealth: 55, recoveryPool: 70, minimumPerGame: 1, fullHealth: 100 },
  dynastyScore: { playoffs: 100, seriesWin: 150, conferenceFinals: 250, finals: 400, championship: 1000, eliteSeasonWins: 60, eliteSeason: 300 },
} as const;
